Extracted to components
ezlint/ezlint pull request #33
Opened 2020-09-25 16:00 UTC by vabatta

2020-09-25 18:27 UTC, giovannifilannino submitted a review, later dismissed

2020-09-27 01:27 UTC, jamescallumyoung approved these changes
LGTM 👍

2020-09-27 01:31 UTC, jamescallumyoung requested changes
One of these is an organism, the other is a molecule. I think they both ought to be the same. They could both be molecules since they're simple enough.

2020-09-29 00:06 UTC, jamescallumyoung approved these changes
LGTM!

2020-09-29 17:57 UTC, merged